export const user = {
  data: {
    bib_data: {
      mms_id: "997924640101921",
      bib_suppress_from_publishing: "false",
      title: "Red Army handbook 1939-45 /",
      author: "Zaloga, Steve",
      issn: null,
      isbn: "0750917407",
      complete_edition: "",
      network_number: [Array],
      place_of_publication: "Gloucestershire :",
      date_of_publication: "1998.",
      publisher_const: "Sutton Publishing",
      link: "https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/997924640101921",
    },
    holding_data: {
      holding_id: "22232355140001921",
      holding_suppress_from_publishing: "false",
      permanent_call_number_type: [Object],
      permanent_call_number: "D764 .Z34 1998",
      call_number_type: [Object],
      call_number: "D764 .Z34 1998",
      accession_number: "",
      copy_id: "",
      in_temp_location: false,
      temp_library: { desc: "" },
      temp_location: { desc: "" },
      temp_call_number_type: [Object],
      temp_call_number: "",
      temp_call_number_source: "",
      temp_policy: [Object],
      link: "https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/997924640101921/holdings/22232355140001921",
    },
    item_data: {
      pid: "23232355130001921",
      barcode: "39097006597927",
      creation_date: "2014-03-04Z",
      modification_date: "2022-07-07Z",
      base_status: [Object],
      awaiting_reshelving: false,
      physical_material_type: [Object],
      policy: [Object],
      provenance: [Object],
      po_line: "",
      is_magnetic: false,
      year_of_issue: "",
      enumeration_a: "",
      enumeration_b: "",
      enumeration_c: "",
      enumeration_d: "",
      enumeration_e: "",
      enumeration_f: "",
      enumeration_g: "",
      enumeration_h: "",
      chronology_i: "",
      chronology_j: "",
      chronology_k: "",
      chronology_l: "",
      chronology_m: "",
      break_indicator: [Object],
      pattern_type: [Object],
      linking_number: "",
      type_of_unit: "",
      description: "",
      replacement_cost: 890,
      receiving_operator: "import",
      process_type: [Object],
      inventory_number: "",
      inventory_date: "2022-07-07Z",
      inventory_price: "",
      library: [Object],
      location: [Object],
      alternative_call_number: "",
      alternative_call_number_type: [Object],
      storage_location_id: "",
      pages: "",
      pieces: "",
      public_note: "",
      fulfillment_note: "",
      internal_note_1: "",
      internal_note_2: "",
      internal_note_3: "Testing Form loading bar.",
      statistics_note_1: "",
      statistics_note_2: "No. Loans: 002 | LastDateReturn: 20080513",
      statistics_note_3: "Maintenance count: 001",
      requested: false,
      edition: null,
      imprint: null,
      language: null,
      physical_condition: [Object],
    },
    link: "https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/997924640101921/holdings/22232355140001921/items/23232355130001921",
  },
};
